### ISSUE TITLE
Lettera crash after install.

### ISSUE THREAD

**Issue by warp9pnt9** [textbrowser/lettera#1] opened 2019-12-24 12:05 UTC
Installed Lettera (both preview versions previously sent, same result).

After install, dialog pops up indicating app crash.

"Unforunately, Lettera has stopped."

About 2 seconds later, a 2nd crash.

I looked on the home screens but did not see the Lettera icon.  I found it in the Apps and dragged to Home screen.

Attempted to run, same result.

It took about 10-15 seconds until I got to the installed apps dialog.  There were no subsequent message pop ups during that time.

I forced stop then uninstalled.  No apparent issues.

Repeated with the other version, same result.

Android 5.0
Samsung SM-N9005

**Comment by textbrowser** [comment] 2019-12-25 01:42
Installing Android 5.0 AVD. Will test soon. Thank you!

**Comment by textbrowser** [comment] 2019-12-25 02:08
Many compilation errors because of older API. Many.

**Comment by textbrowser** [comment] 2019-12-25 02:26
Compilation errors corrected.

**Comment by warp9pnt9** [comment] 2019-12-25 09:40
Any effect upon features or peformance for either older or newer APIs?  Graceful reduction, if any?  How much work was involved?

And thanks and Merry Christmas if you celebrate that!

**Comment by textbrowser** [comment] 2019-12-25 12:39
One fancy menu required attention. Another one remains dysfunctional. The commit will reflect the amount of work. :) If there is any degradation, it will depend on the device and Android version.

Merry Christmas too!

**Comment by textbrowser** [comment] 2019-12-25 14:39
Change set one.

https://github.com/textbrowser/lettera/commit/d40c4d4f1de8e712b7352952edd0ab89a440f842

**Comment by textbrowser** [comment] 2019-12-25 15:20
Set two.

https://github.com/textbrowser/lettera/commit/29f12bcb528274123345c72672830b37530104d7

**Comment by textbrowser** [comment] 2019-12-25 16:50
The texts in the progress dialogs are invisible. The background surrounding a dialog is also mangled. I do not know the causes of these problems. First, the invisible text.

**Comment by textbrowser** [comment] 2019-12-25 17:18
Backgrounds corrected. Including a build for testing. Will now look at the text.

[lettera.zip](https://github.com/textbrowser/lettera/files/4000671/lettera.zip)

**Comment by warp9pnt9** [comment] 2019-12-27 10:47
Seems to run, though not fully tested.  I do not ever use IMAP.  I'll have to set up a test account with IMAP.

**Comment by textbrowser** [comment] 2019-12-27 13:42
The progress dialogs are incorrect. Neither button, nor progress bar, nor text are visible. I've tested all other functions and they are fine. I'm wondering about Android 6, 7, 8, 10 and minor versions.

**Comment by textbrowser** [comment] 2020-01-03 16:05
Dialogs are now visible on Android 5.

[lettera.zip](https://github.com/textbrowser/lettera/files/4019814/lettera.zip)

**Comment by textbrowser** [comment] 2020-01-03 16:07
Closing. Will test on both Android 5 and device-specific version as development progresses.

**Closed as completed by textbrowser** 2020-01-03 16:07 UTC
Labels: Enhancement
